# -*- coding: utf-8 -*-
"""label_preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PKi0vRO9r0C0Cpk3_hqHHgVePSEtHE_p
"""

from google import genai
import os
from dotenv import load_dotenv
load_dotenv()
GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY")

client = genai.Client(api_key=GOOGLE_API_KEY)
model = 'text-embedding-004'

import json
import os

def read_json_file(file_path):
    try:
        with open(file_path, 'r') as file:
            data = json.load(file)
            return data
    except FileNotFoundError:
        print(f"The file {file_path} was not found.")
    except json.JSONDecodeError:
        print(f"Error decoding JSON from the file {file_path}.")

class DictListProcessor:
    """
    A class to process a list of dictionaries with the same keys.
    """
    def __init__(self, data):
        """
        Initializes the processor with a list of dictionaries and calculates unique values.

        Args:
            data (list): A list of dictionaries with the same keys.
        """
        if not isinstance(data, list) or not all(isinstance(d, dict) for d in data):
            raise ValueError("Input data must be a list of dictionaries.")
        if len(data) > 0 and not all(d.keys() == data[0].keys() for d in data):
             raise ValueError("All dictionaries in the list must have the same keys.")

        self.data = data
        self._unique_values = {}
        self._entity_embeddings = {}
        self._entity_clusters = {}

        self._find_unique_values()


    def _find_unique_values(self):
        """
        Calculates and stores all unique values for each key in the data.
        This method is intended for internal use within the class.
        """
        if not self.data:
            print("The data list is empty. Cannot find unique values.")
            return

        # Initialize _unique_values with empty sets for each key
        for key in self.data[0].keys():
          if key != 'image_url'and "random_key":
            self._unique_values[key] = set()

        # Iterate through each dictionary and add values to the sets
        for d in self.data:
            for key, value in d.items():
              if key != 'image_url'and "random_key":
                if isinstance(value, list):
                  for v in value:
                    self._unique_values[key].add(v) # Convert list to tuple before adding to set
                else:
                  self._unique_values[key].add(value)

        for key in self._unique_values.keys():
          self._unique_values[key] = list(self._unique_values[key])

    def get_unique_values(self):
        """
        Returns the dictionary containing unique values for each key.

        Returns:
            dict: A dictionary where keys are the original dictionary keys
                  and values are lists of unique values.
        """
        return self._unique_values

    def get_entity_names(self):
        """
        Returns a list of the entity names (keys of the unique values dictionary).

        Returns:
            list: A list of entity names.
        """
        return list(self._unique_values.keys())

    def get_entity_clusters(self, entity_name):
        """
        Returns the dictionary containing clusters for each entity name.

        Returns:
            string: the name of the entity name
            dict: A dictionary where keys are entity names and values are unique values of entity names.
        """
        return self._entity_clusters[entity_name]


    def set_entity_clusters(self, entity_name, dict_):
        """
        Set the dictionary containing clusters for each entity name.

        Args:
            string: the name of the entity name
            dict: A dictionary where keys are entity names and values are unique values of entity names.
        """
        self._entity_clusters[entity_name] = dict_
        # self.get_entity_clusters(entity_name)


    def change_cluster_name(self, entity_name, old_cluster, new_cluster):
        """
        Change the name of a cluster.

        Args:
            string: old name of the cluster.
            string: new name of the cluster.
        """
        if old_cluster not in self._entity_clusters[entity_name].keys():
          return f'No such {old_cluster} cluster existed; No change is made.'
        if new_cluster in self._entity_clusters[entity_name].keys():
          return f'The {new_cluster} cluster already exists; No change is made.'
        self._entity_clusters[entity_name][new_cluster] = self._entity_clusters[entity_name].pop(old_cluster)
        return self.get_entity_clusters(entity_name)

    def swap_value_cluster(self, entity_name, value, old_cluster, new_cluster):
        """
        Put the value of a cluster to another.

        Args:
            string: value to be swapped.
            string: the cluster name containing the value.
            string: the cluster name that the value is going to be part of it.
        """
        if old_cluster not in self._entity_clusters[entity_name].keys():
          return f'No such {old_cluster} cluster existed; No change is made.'
        if new_cluster not in self._entity_clusters[entity_name].keys():
          return f'No such {new_cluster} cluster existed; No change is made.'

        if isinstance(value, list):
          for v in value:
            if v not in self._entity_clusters[entity_name][old_cluster]:
              return f'No such value {v} in {old_cluster} cluster existed; No change is made.'
        else:
          if value not in self._entity_clusters[entity_name][old_cluster]:
            return f'No such value {value} in {old_cluster} cluster existed; No change is made.'

        if isinstance(value, list):
          for v in value:
            self._entity_clusters[entity_name][new_cluster].append(v)
            self._entity_clusters[entity_name][old_cluster].remove(v)

        else:
          self._entity_clusters[entity_name][new_cluster].append(value)
          self._entity_clusters[entity_name][old_cluster].remove(value)

        return self.get_entity_clusters(entity_name)

    def merge_cluster(self, entity_name, first_cluster, second_cluster):
        """
        Merge two clusters with the name of the first cluster.

        Args:
            string: the first cluster name.
            string: the second cluster name.
        """
        if first_cluster not in self._entity_clusters[entity_name].keys():
          return f'No such {first_cluster} cluster existed; No change is made.'
        if isinstance(second_cluster, list):
          for c in second_cluster:
            if c not in self._entity_clusters[entity_name].keys():
              return f'No such {c} cluster existed; No change is made.'
        else:
          if second_cluster not in self._entity_clusters[entity_name].keys():
            return f'No such {second_cluster} cluster existed; No change is made.'

        if isinstance(second_cluster, list):
          for c in second_cluster:
            self._entity_clusters[entity_name][first_cluster].extend(self._entity_clusters[entity_name][c])
            self._entity_clusters[entity_name].pop(c)

        else:
          self._entity_clusters[entity_name][first_cluster].extend(self._entity_clusters[entity_name][second_cluster])
          self._entity_clusters[entity_name].pop(second_cluster)

        return self.get_entity_clusters(entity_name)

    def create_cluster(self, entity_name, cluster_name):
        """
        Create a new cluster

        Args:
            string: the new cluster name.
        """
        if cluster_name in self._entity_clusters[entity_name].keys():
          return f'The {cluster_name} cluster already exists; No change is made.'

        self._entity_clusters[entity_name][cluster_name] = []
        return self.get_entity_clusters(entity_name)

entity_values = read_json_file('shoes_all.json')
my_product = DictListProcessor(entity_values)

import google.generativeai as genai
import json

model = 'gemini-2.5-flash'

# base_prompt_config = """These are unique values of entity '{entity_name}'. Cluster these values: '{values}'
# Return the result as a JSON object.
# The JSON object should have keys for each cluster, whose value is the corresponding unique values of entity '{entity_name}'. All the keys must be related to '{entity_name}'. The values may have miss spelled or in different languages, handle them and put them in the correct dataset based on their semantic meaning.  If there are unrelated, vague or unspecified values put them in a key named 'unrelated'.
# """

# example_config = """e.g. For entity color with values ['قرمز', 'سرخ', 'green', 'زیتونی', 'زرد', 'یشمی', 'بلند', 'لیمویی', 'بنفش', 'lilac'] the result should be:
# {'green': ['green', 'زیتونی', 'یشمی'],
# 'yellow': ['زرد', 'لیمویی'],
# 'red': ['قرمز', 'سرخ'],
# 'purple': ['بنفش', 'lilac'],
# 'unrelated': ['بلند']
# }
# """


base_prompt_config = """These are unique values of the entity '{entity_name}': '{values}'.
Cluster these values and return the result as a JSON object.

The JSON object should have keys for each cluster, where each key represents the cluster name in **Persian (Farsi)**,
and its value is a list of the corresponding unique values related to that cluster.

Instructions:
- All cluster names and the entire JSON output must be written in Persian (Farsi).
- Group together values with similar meanings, even if they are misspelled or written in different languages.
- All clusters must be relevant to the entity '{entity_name}'.
- If some values are unrelated, vague, or unspecified, place them under a cluster named 'نامرتبط'.
"""

example_config = """For example, for the entity 'color' with values
['قرمز', 'سرخ', 'green', 'زیتونی', 'زرد', 'یشمی', 'بلند', 'لیمویی', 'بنفش', 'lilac'],
the output should be:

{
'سبز': ['green', 'زیتونی', 'یشمی'],
'زرد': ['زرد', 'لیمویی'],
'قرمز': ['قرمز', 'سرخ'],
'بنفش': ['بنفش', 'lilac'],
'نامرتبط': ['بلند']
}
"""


for entity_name, unique_values in my_product.get_unique_values().items():
    print(f"Requesting clustering for entity: {entity_name} with {len(unique_values)} values!")
    prompt = base_prompt_config.format(entity_name=entity_name, values=unique_values) + example_config

    try:
        response = client.models.generate_content(model=model,
                                                  contents=prompt).text

        try:
            json_start = response.find("```json")
            json_end = response.rfind("```")

            if json_start != -1 and json_end != -1 and json_end > json_start:
                json_string = response[json_start + 7 : json_end].strip()
            else:
                json_string = response.strip()


            print(f"Received and parsed clustering results for {entity_name}")
            my_product.set_entity_clusters(entity_name ,json.loads(json_string))

        except json.JSONDecodeError as e:
            print(f"Error decoding JSON response for entity {entity_name}: {e}")
        except Exception as parse_error:
            print(f"An unexpected error occurred during JSON parsing for entity {entity_name}: {parse_error}")


    except Exception as e:
        print(f"Error requesting clustering for entity {entity_name}: {e}")

def manage_clusters(processor, entity_name):
    """
    Manages cluster operations based on user input.

    Args:
        processor (DictListProcessor): An instance of the DictListProcessor class.
    """
    result = processor.get_entity_clusters(entity_name)
    for ent in result.keys():
      print(ent)
      print(result[ent])

    print("Enter the action you want to perform:")
    print("1. Change cluster name")
    print("2. Swap value(s) between clusters")
    print("3. Merge clusters")
    print("4. Create a new cluster")
    print("Enter 'exit' to quit.")

    while True:
        choice = input("Enter your choice (1-4 or 'exit'): ").strip().lower()

        if choice == 'exit':
            print("Exiting cluster management.")
            break
        elif choice == '1':
            old_name = input("Enter the current cluster name: ").strip()
            new_name = input("Enter the new cluster name: ").strip()
            result = processor.change_cluster_name(entity_name, old_name, new_name)
            print(result)
        elif choice == '2':
            values_to_swap = []
            while True:
                value = input("Enter a value to swap (enter 0 when done): ").strip()
                if value == '0':
                    break
                values_to_swap.append(value)

            if not values_to_swap:
                print("No values entered to swap.")
                continue

            old_cluster = input("Enter the cluster name containing the value(s): ").strip()
            new_cluster = input("Enter the target cluster name: ").strip()
            result = processor.swap_value_cluster(entity_name, values_to_swap, old_cluster, new_cluster)
            print(result)
        elif choice == '3':
            first_cluster = input("Enter the name of the first cluster to merge: ").strip()
            second_clusters_to_merge = []
            while True:
                cluster_to_merge = input("Enter a cluster name to merge into the first cluster (enter 0 when done): ").strip()
                if cluster_to_merge == '0':
                    break
                second_clusters_to_merge.append(cluster_to_merge)

            if not second_clusters_to_merge:
                print("No clusters entered to merge.")
                continue

            result = processor.merge_cluster(entity_name, first_cluster, second_clusters_to_merge)
            print(result)
        elif choice == '4':
            cluster_name = input("Enter the name for the new cluster: ").strip()
            result = processor.create_cluster(entity_name, cluster_name)
            print(result)
        else:
            print("Invalid choice. Please enter a number between 1 and 4, or 'exit'.")

for entity_name in my_product.get_unique_values().keys():
  print(entity_name)
  manage_clusters(my_product, entity_name)